project:
  type: book
  output-dir: docs

book:
  title: "BIO144 Course Book (version 2026)"
  author: "Owen Petchey"
  date: today
  reader-mode: true

  page-footer:
    left: |
      BIO144 Data Analysis for Biologists, Course Book written by Owen Petchey
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.png
  favicon: cover.png
  site-url: https://opetchey.github.io/BIO144_Course_Book/
  repo-url: https://github.com/opetchey/BIO144_Course_Book/
  repo-branch: main
  repo-actions: [edit, issue]

  chapters:
    - index.qmd
    - 1.1-intro.qmd
    - 2.1-R-and-RStudio.qmd
    - 4.1-regression-part1.qmd
    - 5.1-regression-part2.qmd
    - 6.1-anova.qmd
    - 7.1-multiple-explanatory-variables-part1.qmd
   

format:
  html:
    theme: cosmo
    fig-width: 5
    fig-height: 5
    fig-align: center
  pdf:
    keep-tex: true
    documentclass: book
    classoption:
      - 8pt
      - a4paper
    toc-depth: 2

    
execute: 
  echo: false
  

